version: 2

sources:
  - name: raw_rcbc
    database: "{{ env_var('CATALOG') }}"
    schema: raw_rcbc  
    tables:
      - name: payroll_casa
      - name: payroll_icard

models:
  - name: stg_payroll_casa
    description: ""
    columns:
    - name: rec_type
      data_type: string
      description: ""
      
    - name: batch_id
      data_type: string
      description: ""

    - name: batch_date
      data_type: date
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

    - name: serial_number
      data_type: string
      description: ""

    - name: category_of_interface
      data_type: string
      description: ""

    - name: currency
      data_type: string
      description: ""

    - name: tran_type
      data_type: string
      description: ""

    - name: tran_sub_type
      data_type: string
      description: ""

    - name: tran_date
      data_type: date
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

    - name: value_date
      data_type: date
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

    - name: initiating_sol
      data_type: string
      description: ""

    - name: gi_date
      data_type: date
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

    - name: tran_amount
      data_type: double
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: double

    - name: act_no
      data_type: string
      description: ""

    - name: tran_particular
      data_type: string
      description: ""

    - name: part_tran_type
      data_type: string
      description: ""

    - name: office_account_placeholder
      data_type: string
      description: ""

    - name: bank_id
      data_type: string
      description: ""

    - name: company_account
      data_type: string
      description: ""

    - name: branch
      data_type: string
      description: ""

    - name: company_code
      data_type: string
      description: ""

    - name: handoff_name
      data_type: string
      description: ""

    - name: existasof
      data_type: date
      description: ""
      tests:
        - not_null
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

  - name: stg_payroll_icard
    description: ""
    columns:
    - name: rec_type
      data_type: string
      description: ""
      
    - name: act_no
      data_type: string
      description: ""

    - name: tran_amount
      data_type: double
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: double

    - name: payee
      data_type: string
      description: ""

    - name: company_account
      data_type: string
      description: ""

    - name: co_name
      data_type: string
      description: ""

    - name: tran_date
      data_type: date
      description: ""
      tests:
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"

    - name: tran_date_orig
      data_type: string
      description: ""

    - name: existasof
      data_type: date
      description: ""
      tests:
        - not_null
        - dbt_expectations.expect_column_values_to_be_of_type:
            column_type: date
        - dbt_expectations.expect_column_values_to_match_regex:
            regex: "^[0-9]{4}-[0-9]{2}-[0-9]{2}$"
